# Generated by Django 5.0.1 on 2024-01-22 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courselibrary', '0002_alter_tee_course_rating_alter_tee_slope_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_holes', models.CharField(choices=[('F9', 'Front 9'), ('B9', 'Back 9'), ('18', '18 Holes')], max_length=2)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('weather_conditions', models.IntegerField(blank=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='courselibrary.course')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tees', to='courselibrary.course')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.IntegerField()),
                ('par', models.IntegerField()),
                ('score', models.IntegerField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rounds.round')),
            ],
        ),
    ]
