# Generated by Django 5.0.1 on 2024-01-22 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courselibrary', '0002_alter_tee_course_rating_alter_tee_slope_rating'),
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courselibrary.course'),
        ),
        migrations.AlterField(
            model_name='round',
            name='tees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courselibrary.tee'),
        ),
    ]
