# Generated by Django 5.0.1 on 2024-01-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0002_alter_round_course_alter_round_tees'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='yardage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
