# Generated by Django 5.0.1 on 2024-01-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0004_alter_round_weather_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
