# Generated by Django 5.0.1 on 2024-02-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0005_round_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
