# Generated by Django 5.0.1 on 2024-01-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courselibrary', '0002_alter_tee_course_rating_alter_tee_slope_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tee',
            old_name='name',
            new_name='tee_name',
        ),
    ]
