# Generated by Django 5.0.1 on 2024-01-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courselibrary', '0003_rename_name_tee_tee_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tee',
            old_name='tee_name',
            new_name='name',
        ),
    ]
